/**
 * Dataset Export Service
 * Core logic for exporting annotated datasets in YOLO/COCO format
 */

const fs = require('fs').promises;
const path = require('path');
const archiver = require('archiver');
const crypto = require('crypto');
const Annotation = require('../models/Annotation');
const storage = require('./storage');
const {
  convertSubboxesToYOLO,
  formatYOLOSubboxText,
  validateYOLOCoordinates
} = require('./annotationService');
const {
  DEFAULT_SPLIT_RATIO,
  TEMP_DIR_PATH,
  EXPORT_FORMATS,
  YOLO_CLASS_NAMES,
  ANNOTATION_STATUS,
  BATCH_SIZE,
  ERROR_CODES,
  SPLIT_STRATEGY,
  MIN_FREE_DISK_SPACE
} = require('../constants/export');

/**
 * Ensure temp directory exists
 */
async function ensureTempDir() {
  try {
    await fs.mkdir(TEMP_DIR_PATH, { recursive: true });
  } catch (error) {
    throw new Error(`Failed to create temp directory: ${error.message}`);
  }
}

/**
 * Check available disk space
 * @returns {Promise<number>} - Available space in bytes
 */
async function checkDiskSpace() {
  try {
    const { exec } = require('child_process');
    const { promisify } = require('util');
    const execPromise = promisify(exec);
    
    const { stdout } = await execPromise(`df -k ${TEMP_DIR_PATH} | tail -1 | awk '{print $4}'`);
    const availableKB = parseInt(stdout.trim());
    return availableKB * 1024; // Convert to bytes
  } catch (error) {
    console.warn('Could not check disk space:', error.message);
    return MIN_FREE_DISK_SPACE; // Assume enough space
  }
}

/**
 * Split dataset by patient to avoid data leakage
 * @param {Array} images - Array of image records
 * @param {Object} splitRatio - { train, val, test }
 * @returns {Promise<Object>} - { train: [...imageIds], val: [...], test: [...] }
 */
async function splitDatasetByPatient(images, splitRatio = DEFAULT_SPLIT_RATIO) {
  // Validate split ratios
  const sum = splitRatio.train + splitRatio.val + splitRatio.test;
  // Allow sum = 0 (no split) or sum = 1.0 (valid split)
  if (sum > 0 && Math.abs(sum - 1.0) > 0.001) {
    throw new Error(`${ERROR_CODES.INVALID_SPLIT_RATIO}: Ratios must sum to 1.0, got ${sum}`);
  }
  
  // Only check minimum if splits are being used
  if (sum > 0) {
    if ((splitRatio.train > 0 && splitRatio.train < 0.05) || 
        (splitRatio.val > 0 && splitRatio.val < 0.05) || 
        (splitRatio.test > 0 && splitRatio.test < 0.05)) {
      throw new Error(`${ERROR_CODES.INVALID_SPLIT_RATIO}: Each non-zero split must be at least 5%`);
    }
  }
  
  // Group images by patient
  const imagesByPatient = {};
  images.forEach(img => {
    if (!imagesByPatient[img.patient_id]) {
      imagesByPatient[img.patient_id] = [];
    }
    imagesByPatient[img.patient_id].push(img.id);
  });
  
  // Get unique patient IDs and shuffle
  const patientIds = Object.keys(imagesByPatient);
  const shuffled = patientIds.sort(() => Math.random() - 0.5);
  
  // Split patients
  const trainCount = Math.floor(shuffled.length * splitRatio.train);
  const valCount = Math.floor(shuffled.length * splitRatio.val);
  
  const trainPatients = shuffled.slice(0, trainCount);
  const valPatients = shuffled.slice(trainCount, trainCount + valCount);
  const testPatients = shuffled.slice(trainCount + valCount);
  
  // Assign images to splits
  const splits = {
    train: trainPatients.flatMap(pid => imagesByPatient[pid]),
    val: valPatients.flatMap(pid => imagesByPatient[pid]),
    test: testPatients.flatMap(pid => imagesByPatient[pid])
  };
  
  return splits;
}

/**
 * Generate data.yaml for YOLO training
 * @param {Object} splits - { train, val, test }
 * @returns {string} - YAML content
 */
function generateDataYaml(splits) {
  return `# YOLO Dataset Configuration
# Generated by NhaKhoa System

train: ./images/train
val: ./images/val
test: ./images/test

nc: 2
names: ['no_plaque', 'has_plaque']

# Dataset statistics
# Train images: ${splits.train.length}
# Val images: ${splits.val.length}
# Test images: ${splits.test.length}
# Total: ${splits.train.length + splits.val.length + splits.test.length}
`;
}

/**
 * Generate classes.txt file
 * @returns {string} - Class names one per line
 */
function generateClassesTxt() {
  return YOLO_CLASS_NAMES.join('\n');
}

/**
 * Sanitize filename for safe file system operations
 * @param {string} filename - Original filename
 * @returns {string} - Sanitized filename
 */
function sanitizeFilename(filename) {
  return filename
    .replace(/[^a-zA-Z0-9._-]/g, '_')
    .replace(/_{2,}/g, '_')
    .toLowerCase();
}

/**
 * Extract object name from MinIO URL
 * @param {string} url - MinIO URL
 * @returns {string} - Object name
 */
function extractObjectName(url) {
  // URL format: /nhakhoa/visits/123/image.jpg
  // MinIO object format: visits/123/image.jpg (without bucket name)
  return storage.extractObjectName(url);
}

/**
 * Download image from MinIO
 * @param {string} url - MinIO URL
 * @param {string} destPath - Destination file path
 */
async function downloadImage(url, destPath) {
  try {
    const objectName = extractObjectName(url);
    const buffer = await storage.downloadFile(objectName);
    await fs.writeFile(destPath, buffer);
  } catch (error) {
    console.error(`Failed to download image ${url}:`, error.message);
    throw error;
  }
}

/**
 * Process images in batches to avoid memory overflow
 * @param {Array} items - Items to process
 * @param {Function} processFn - Async function to process each item
 * @param {number} batchSize - Batch size
 */
async function processBatch(items, processFn, batchSize = BATCH_SIZE) {
  const results = [];
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    const batchResults = await Promise.all(batch.map(processFn));
    results.push(...batchResults);
  }
  return results;
}

/**
 * Generate YOLO dataset
 * @param {Object} params - { visitIds, patientIds, splitRatio, filters, format }
 * @returns {Promise<Object>} - { exportId, zipPath, stats }
 */
async function generateYOLODataset(params) {
  const {
    visitIds,
    patientIds = null,
    splitRatio = DEFAULT_SPLIT_RATIO,
    filters = {},
    format = EXPORT_FORMATS.YOLO
  } = params;
  
  // Check disk space
  const availableSpace = await checkDiskSpace();
  if (availableSpace < MIN_FREE_DISK_SPACE) {
    throw new Error(`${ERROR_CODES.INSUFFICIENT_SPACE}: Only ${(availableSpace / 1024 / 1024 / 1024).toFixed(2)}GB available`);
  }
  
  // Create export directory
  await ensureTempDir();
  const exportId = `exp_${crypto.randomUUID()}`;
  const exportDir = path.join(TEMP_DIR_PATH, exportId);
  await fs.mkdir(exportDir, { recursive: true });
  
  try {
    // 1. Fetch exportable images
    console.log(`Fetching annotated images for visits: ${visitIds.join(', ')}`);
    const images = await Annotation.getFullyAnnotatedImages(visitIds, filters);
    
    if (images.length === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No fully annotated images found`);
    }
    
    console.log(`Found ${images.length} exportable images`);
    
    // 2. Split dataset by patient
    console.log('Splitting dataset by patient...');
    const splits = await splitDatasetByPatient(images, splitRatio);
    
    // 3. Fetch all subboxes for export
    const imageIds = images.map(img => img.id);
    console.log(`Fetching subboxes for ${imageIds.length} images...`);
    const allSubboxes = await Annotation.getSubboxesForExport(imageIds);
    
    // Group subboxes by image_id
    const subboxesByImage = {};
    allSubboxes.forEach(subbox => {
      if (!subboxesByImage[subbox.image_id]) {
        subboxesByImage[subbox.image_id] = [];
      }
      subboxesByImage[subbox.image_id].push(subbox);
    });
    
    // 4. Create directory structure
    const splitNames = ['train', 'val', 'test'];
    for (const split of splitNames) {
      await fs.mkdir(path.join(exportDir, 'images', split), { recursive: true });
      await fs.mkdir(path.join(exportDir, 'labels', split), { recursive: true });
    }
    
    // 5. Process images and generate YOLO labels
    let processedCount = 0;
    let skippedCount = 0;
    const stats = {
      totalImages: 0,
      totalSubboxes: 0,
      plaquePositive: 0,
      plaqueNegative: 0,
      splits: { train: 0, val: 0, test: 0 }
    };
    
    for (const [splitName, imageIdsInSplit] of Object.entries(splits)) {
      console.log(`Processing ${splitName} split: ${imageIdsInSplit.length} images`);
      
      for (const imageId of imageIdsInSplit) {
        try {
          const image = images.find(img => img.id === imageId);
          if (!image) {
            console.warn(`Image ${imageId} not found in images array`);
            continue;
          }
          
          const subboxes = subboxesByImage[imageId] || [];
          
          // Allow images with no subboxes (negative samples - no objects in image)
          console.log(`Processing image ${imageId}: ${image.original_filename}, subboxes: ${subboxes.length}`);
          
          // Sanitize filename
          const sanitizedName = sanitizeFilename(image.original_filename);
          const baseName = path.parse(sanitizedName).name;
          const imageExt = path.parse(image.original_filename).ext || '.jpg';
          
          // Download image
          const imageDest = path.join(exportDir, 'images', splitName, `${baseName}${imageExt}`);
          console.log(`Downloading from ${image.url} to ${imageDest}`);
          await downloadImage(image.url, imageDest);
          
          // If no subboxes, create empty label file (negative sample)
          if (subboxes.length === 0) {
            const labelDest = path.join(exportDir, 'labels', splitName, `${baseName}.txt`);
            await fs.writeFile(labelDest, ''); // Empty file = no objects
            console.log(`Created empty label file for negative sample: ${labelDest}`);
            processedCount++;
            stats.totalImages++;
            stats.splits[splitName]++;
            continue;
          }

          // Convert subboxes to YOLO format
          const yoloSubboxes = convertSubboxesToYOLO(subboxes, image.width, image.height);
          
          // Validate coordinates
          const validSubboxes = yoloSubboxes.filter(yolo => {
            const valid = validateYOLOCoordinates(yolo);
            if (!valid) {
              console.warn(`Invalid YOLO coordinates for image ${image.id}, skipping subbox`);
            }
            return valid;
          });
          
          if (validSubboxes.length === 0) {
            skippedCount++;
            continue;
          }
          
          // Write YOLO label file
          const labelContent = formatYOLOSubboxText(validSubboxes);
          const labelDest = path.join(exportDir, 'labels', splitName, `${baseName}.txt`);
          await fs.writeFile(labelDest, labelContent);
          
          // Update stats
          processedCount++;
          stats.totalImages++;
          stats.totalSubboxes += validSubboxes.length;
          stats.plaquePositive += validSubboxes.filter(s => s.class_id === 1).length;
          stats.plaqueNegative += validSubboxes.filter(s => s.class_id === 0).length;
          stats.splits[splitName]++;
          
        } catch (error) {
          console.error(`Failed to process image ${imageId}:`, error.message);
          skippedCount++;
        }
      }
    }
    
    console.log(`Processed: ${processedCount}, Skipped: ${skippedCount}`);
    
    if (processedCount === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No valid images could be processed`);
    }
    
    // 6. Generate data.yaml and classes.txt
    const dataYaml = generateDataYaml(stats.splits);
    await fs.writeFile(path.join(exportDir, 'data.yaml'), dataYaml);
    await fs.writeFile(path.join(exportDir, 'classes.txt'), generateClassesTxt());
    
    // 7. Generate README
    const readme = `# NhaKhoa Plaque Detection Dataset

## Dataset Information
- **Export ID**: ${exportId}
- **Generated**: ${new Date().toISOString()}
- **Format**: YOLO v5/v8/v11 compatible
- **Classes**: 2 (no_plaque, has_plaque)

## Statistics
- **Total Images**: ${stats.totalImages}
- **Total Subboxes**: ${stats.totalSubboxes}
- **Plaque Positive**: ${stats.plaquePositive}
- **Plaque Negative**: ${stats.plaqueNegative}

## Split Distribution
- **Train**: ${stats.splits.train} images
- **Val**: ${stats.splits.val} images
- **Test**: ${stats.splits.test} images

## Directory Structure
\`\`\`
dataset/
├── images/
│   ├── train/
│   ├── val/
│   └── test/
├── labels/
│   ├── train/
│   ├── val/
│   └── test/
├── data.yaml
└── classes.txt
\`\`\`

## YOLO Label Format
Each label file contains annotations in 6-field format:
\`<class> <x_center> <y_center> <width> <height> <parent_tooth_class>\`

Where:
- \`class\`: 0 (no_plaque) or 1 (has_plaque)
- \`x_center, y_center, width, height\`: Normalized [0-1] coordinates
- \`parent_tooth_class\`: YOLO class ID of parent tooth (0-15)

## Training with YOLOv8
\`\`\`python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Train
model.train(data='data.yaml', epochs=100, imgsz=640)
\`\`\`

## Notes
- Dataset split by patient to prevent data leakage
- All coordinates validated and clamped to [0, 1]
- Only fully annotated images included
`;
    await fs.writeFile(path.join(exportDir, 'README.md'), readme);
    
    // 8. Create ZIP archive
    console.log('Creating ZIP archive...');
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19); // 2026-02-01T12-34-56
    const zipFilename = `${exportId}_${timestamp}.zip`;
    const zipPath = path.join(TEMP_DIR_PATH, zipFilename);
    await createZipArchive(exportDir, zipPath);
    
    // 9. Cleanup export directory
    await fs.rm(exportDir, { recursive: true, force: true });
    
    return {
      exportId,
      zipPath,
      stats
    };
    
  } catch (error) {
    // Cleanup on error
    try {
      await fs.rm(exportDir, { recursive: true, force: true });
    } catch (cleanupError) {
      console.error('Failed to cleanup after error:', cleanupError.message);
    }
    throw error;
  }
}

/**
 * Create ZIP archive from directory
 * @param {string} sourceDir - Source directory
 * @param {string} zipPath - Destination ZIP path
 */
async function createZipArchive(sourceDir, zipPath) {
  return new Promise((resolve, reject) => {
    const output = require('fs').createWriteStream(zipPath);
    const archive = archiver('zip', {
      zlib: { level: 6 } // Compression level
    });
    
    output.on('close', () => {
      console.log(`ZIP created: ${archive.pointer()} bytes`);
      resolve();
    });
    
    archive.on('error', (err) => {
      reject(err);
    });
    
    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}

/**
 * Cleanup expired exports
 * @param {number} maxAgeSeconds - Maximum age in seconds
 */
async function cleanupExpiredExports(maxAgeSeconds = 3600) {
  try {
    const files = await fs.readdir(TEMP_DIR_PATH);
    const now = Date.now();
    
    for (const file of files) {
      const filePath = path.join(TEMP_DIR_PATH, file);
      const stat = await fs.stat(filePath);
      const ageSeconds = (now - stat.mtimeMs) / 1000;
      
      if (ageSeconds > maxAgeSeconds) {
        await fs.rm(filePath, { recursive: true, force: true });
        console.log(`Cleaned up expired export: ${file}`);
      }
    }
  } catch (error) {
    console.error('Cleanup error:', error.message);
  }
}

/**
 * Generate COCO format dataset
 * @param {Object} params - Export parameters
 * @returns {Promise<Object>} - { exportId, zipPath, stats }
 */
async function generateCOCODataset(params) {
  const {
    visitIds,
    patientIds = null,
    splitRatio = DEFAULT_SPLIT_RATIO,
    filters = {},
    format = EXPORT_FORMATS.COCO
  } = params;
  
  // Check disk space
  const availableSpace = await checkDiskSpace();
  if (availableSpace < MIN_FREE_DISK_SPACE) {
    throw new Error(`${ERROR_CODES.INSUFFICIENT_SPACE}: Only ${(availableSpace / 1024 / 1024 / 1024).toFixed(2)}GB available`);
  }
  
  // Create export directory
  await ensureTempDir();
  const exportId = `exp_${crypto.randomUUID()}`;
  const exportDir = path.join(TEMP_DIR_PATH, exportId);
  await fs.mkdir(exportDir, { recursive: true });
  
  try {
    // 1. Fetch exportable images
    console.log(`Fetching annotated images for visits: ${visitIds.join(', ')}`);
    const images = await Annotation.getFullyAnnotatedImages(visitIds, filters);
    
    if (images.length === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No fully annotated images found`);
    }
    
    console.log(`Found ${images.length} exportable images`);
    
    // 2. Split dataset by patient
    console.log('Splitting dataset by patient...');
    const splits = await splitDatasetByPatient(images, splitRatio);
    
    // 3. Fetch all subboxes for export
    const imageIds = images.map(img => img.id);
    console.log(`Fetching subboxes for ${imageIds.length} images...`);
    const allSubboxes = await Annotation.getSubboxesForExport(imageIds);
    
    // Group subboxes by image_id
    const subboxesByImage = {};
    allSubboxes.forEach(subbox => {
      if (!subboxesByImage[subbox.image_id]) {
        subboxesByImage[subbox.image_id] = [];
      }
      subboxesByImage[subbox.image_id].push(subbox);
    });
    
    // 4. Create directory structure for COCO
    const splitNames = ['train', 'val', 'test'];
    for (const split of splitNames) {
      await fs.mkdir(path.join(exportDir, split), { recursive: true });
    }
    
    // 5. Process each split and generate COCO JSON
    let processedCount = 0;
    let skippedCount = 0;
    const stats = {
      totalImages: 0,
      totalSubboxes: 0,
      plaquePositive: 0,
      plaqueNegative: 0,
      splits: { train: 0, val: 0, test: 0 }
    };
    
    for (const [splitName, imageIdsInSplit] of Object.entries(splits)) {
      console.log(`Processing ${splitName} split: ${imageIdsInSplit.length} images`);
      
      // Initialize COCO structure
      const cocoData = {
        info: {
          description: 'NhaKhoa Plaque Detection Dataset',
          version: '1.0',
          year: new Date().getFullYear(),
          contributor: 'NhaKhoa Team',
          date_created: new Date().toISOString().split('T')[0]
        },
        licenses: [{
          id: 1,
          name: 'Proprietary',
          url: ''
        }],
        categories: [
          { id: 0, name: 'no_plaque', supercategory: 'dental' },
          { id: 1, name: 'has_plaque', supercategory: 'dental' }
        ],
        images: [],
        annotations: []
      };
      
      let annotationId = 1;
      let imageIdCounter = 1;
      
      for (const imageId of imageIdsInSplit) {
        try {
          const image = images.find(img => img.id === imageId);
          if (!image) {
            console.warn(`Image ${imageId} not found in images array`);
            continue;
          }
          
          const subboxes = subboxesByImage[imageId] || [];
          
          // Allow images with no subboxes (negative samples)
          console.log(`Processing image ${imageId}: ${image.original_filename}, subboxes: ${subboxes.length}`);
          
          // Sanitize filename
          const sanitizedName = sanitizeFilename(image.original_filename);
          const baseName = path.parse(sanitizedName).name;
          const imageExt = path.parse(image.original_filename).ext || '.jpg';
          const imageName = `${baseName}${imageExt}`;
          
          // Download image
          const imageDest = path.join(exportDir, splitName, imageName);
          console.log(`Downloading from ${image.url} to ${imageDest}`);
          await downloadImage(image.url, imageDest);
          
          // Add image to COCO
          cocoData.images.push({
            id: imageIdCounter,
            file_name: imageName,
            width: image.width,
            height: image.height,
            license: 1,
            date_captured: image.created_at || new Date().toISOString()
          });
          
          // If no subboxes, image has no annotations (negative sample)
          // Just add image entry, no annotations will be added below
          
          // Convert subboxes to COCO annotations
          for (const subbox of subboxes) {
            // Parse bbox từ database - format là [x, y, w, h] in pixels
            const bbox = subbox.bbox; // Already parsed in getSubboxesForExport
            if (!Array.isArray(bbox) || bbox.length < 4) {
              console.warn(`Invalid bbox format for subbox ${subbox.subbox_id}, skipping`);
              continue;
            }
            
            const [x, y, w, h] = bbox;
            
            // Validate and clamp bbox
            const x_min = Math.max(0, x);
            const y_min = Math.max(0, y);
            const x_max = Math.min(image.width, x + w);
            const y_max = Math.min(image.height, y + h);
            const width = x_max - x_min;
            const height = y_max - y_min;
            
            if (width <= 0 || height <= 0) {
              console.warn(`Invalid bbox dimensions for subbox ${subbox.subbox_id}: [${x}, ${y}, ${w}, ${h}], skipping`);
              continue;
            }
            
            // Determine class based on plaque_status
            // plaque_status: 'plaque' | 'no_plaque' | null
            const categoryId = (subbox.plaque_status === 1 || subbox.plaque_status === 'plaque') ? 1 : 0;
            
            cocoData.annotations.push({
              id: annotationId++,
              image_id: imageIdCounter,
              category_id: categoryId,
              bbox: [x_min, y_min, width, height],
              area: width * height,
              iscrowd: 0,
              segmentation: [] // Can be extended with polygon segmentation if needed
            });
            
            // Update stats
            stats.totalSubboxes++;
            if (categoryId === 1) {
              stats.plaquePositive++;
            } else {
              stats.plaqueNegative++;
            }
          }
          
          processedCount++;
          stats.totalImages++;
          stats.splits[splitName]++;
          imageIdCounter++;
          
        } catch (error) {
          console.error(`Failed to process image ${imageId}:`, error.message);
          skippedCount++;
        }
      }
      
      // Write COCO JSON file for this split
      const cocoJsonPath = path.join(exportDir, splitName, `annotations.json`);
      await fs.writeFile(cocoJsonPath, JSON.stringify(cocoData, null, 2));
      console.log(`COCO JSON written: ${cocoJsonPath}`);
    }
    
    console.log(`Processed: ${processedCount}, Skipped: ${skippedCount}`);
    
    if (processedCount === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No valid images could be processed`);
    }
    
    // 6. Generate README
    const readme = `# NhaKhoa Plaque Detection Dataset - COCO Format

## Dataset Information
- **Export ID**: ${exportId}
- **Generated**: ${new Date().toISOString()}
- **Format**: COCO (Common Objects in Context)
- **Classes**: 2 (no_plaque, has_plaque)

## Statistics
- **Total Images**: ${stats.totalImages}
- **Total Subboxes**: ${stats.totalSubboxes}
- **Plaque Positive**: ${stats.plaquePositive}
- **Plaque Negative**: ${stats.plaqueNegative}

## Split Distribution
- **Train**: ${stats.splits.train} images
- **Val**: ${stats.splits.val} images
- **Test**: ${stats.splits.test} images

## Directory Structure
\`\`\`
dataset/
├── train/
│   ├── annotations.json
│   └── <images>
├── val/
│   ├── annotations.json
│   └── <images>
└── test/
    ├── annotations.json
    └── <images>
\`\`\`

## COCO JSON Format
Each annotations.json contains:
- \`info\`: Dataset metadata
- \`licenses\`: License information
- \`categories\`: Class definitions (id: 0=no_plaque, 1=has_plaque)
- \`images\`: List of images with id, file_name, width, height
- \`annotations\`: Bounding boxes with id, image_id, category_id, bbox [x, y, width, height]

## Usage Example (PyTorch)
\`\`\`python
from pycocotools.coco import COCO

# Load annotations
coco_train = COCO('train/annotations.json')

# Get all image IDs
img_ids = coco_train.getImgIds()

# Load an image and its annotations
img_info = coco_train.loadImgs(img_ids[0])[0]
ann_ids = coco_train.getAnnIds(imgIds=img_info['id'])
anns = coco_train.loadAnns(ann_ids)
\`\`\`

## Notes
- Dataset split by patient to prevent data leakage
- All bounding boxes validated and clamped to image dimensions
- Only fully annotated images included
`;
    await fs.writeFile(path.join(exportDir, 'README.md'), readme);
    
    // 7. Create ZIP archive
    console.log('Creating ZIP archive...');
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19); // 2026-02-01T12-34-56
    const zipFilename = `${exportId}_${timestamp}.zip`;
    const zipPath = path.join(TEMP_DIR_PATH, zipFilename);
    await createZipArchive(exportDir, zipPath);
    
    // 8. Cleanup export directory
    await fs.rm(exportDir, { recursive: true, force: true });
    
    return {
      exportId,
      zipPath,
      stats
    };
    
  } catch (error) {
    // Cleanup on error
    try {
      await fs.rm(exportDir, { recursive: true, force: true });
    } catch (cleanupError) {
      console.error('Failed to cleanup after error:', cleanupError.message);
    }
    throw error;
  }
}

module.exports = {
  generateYOLODataset,
  generateCOCODataset,
  splitDatasetByPatient,
  cleanupExpiredExports,
  ensureTempDir,
  checkDiskSpace
};
